### ISSUE TITLE
Warning in ViewController

### ISSUE THREAD

**Issue by appsird** [deege/deegeu-ios-swift-video-camera#1]
I receive a warning on line 49 of ViewController.swift run-in Xcode 7.3 stating:

Use #selector instead of explicitly constructing a 'Selector'.

**Comment by appsird** [comment]
Correction, meant line 80

**Comment by appsird** [comment]
I changed the line to:

let selectorToCall = #selector(videoWasSavedSuccessfully)

compiles without warning, and appears to run properly

**Comment by deege** [comment]
Thanks for the heads up. Updated the code for 7.3
