### ISSUE TITLE
face camera?

### ISSUE THREAD

**Issue by davut5** [deege/deegeu-ios-swift-video-camera#3]
i want to record my video  Front camera only..

**Comment by deege** [comment]
In line 34 of the ViewController, change 

`if UIImagePickerController.availableCaptureModesForCameraDevice(.Rear) != nil {`

to

`if UIImagePickerController.availableCaptureModesForCameraDevice(.Front) != nil {`

**Comment by davut5** [comment]
thank u very much for your answer... but now i understood it was not correct solution for my app. sorry.... :(
i want to record a part of screen video... can u show me a way please. 

i used replaykit for screen record. but it is recording full screen and everything  :(

**Comment by deege** [comment]
It's beyond the scope of this tutorial. You'll have to do some custom video coding using AVFoundation. That's where I'd start.
